on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux:
    name: Release Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: wangyoucao577/go-release-action@ec4e3151b3eccfa3527868ba70f60402265fef06 # v1.54
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}

  release-darwin:
    name: Release macOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: wangyoucao577/go-release-action@ec4e3151b3eccfa3527868ba70f60402265fef06 # v1.54
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: ${{ matrix.goarch }}

  release-windows:
    name: Release Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: wangyoucao577/go-release-action@ec4e3151b3eccfa3527868ba70f60402265fef06 # v1.54
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: ${{ matrix.goarch }}
          archive_format: zip
