name: ci

# future: develop branch no push
on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: jfryy/qq
          tags: v1, latest
          multiPlatform: true
          registry: registry.hub.docker.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
